---
label: 'Training ride #3 2021'
hide_body: false
fields:
- type: text
  name: title
  label: title
- type: datetime
  name: date
  label: date
- type: text
  name: weight
  label: weight
- type: text
  name: author
  label: author
- type: file
  name: image
  label: image
- type: text
  name: description
  label: description
- type: textarea
  name: tease
  label: tease
- type: list
  name: tags
  label: tags
- type: text
  name: featured
  label: featured
